//constants type
const SET_DATA_LIST = 'SET_DATA_LIST';

//constants actionSaga
const GET_ACTION_DATA_API = 'GET_ACTION_DATA_API';
const POST_ACTION_DATA_API = 'POST_ACTION_DATA_API';
const CHECK_ACTION_DATA_API = 'CHECK_ACTION_DATA_API';
const REJECT_ACTION_DATA_API = 'REJECT_ACTION_DATA_API';
const DEL_ACTION_DATA_API = 'DEL_ACTION_DATA_API';


export {
    SET_DATA_LIST,

    GET_ACTION_DATA_API,
    POST_ACTION_DATA_API,
    CHECK_ACTION_DATA_API,
    REJECT_ACTION_DATA_API,
    DEL_ACTION_DATA_API,
};